### ISSUE TITLE
how can send to server 'GBK'

### ISSUE THREAD

**Issue by tmcyfy** [iliakan/mud-client#2]
how can send to server 'GBK' character ?

**Comment by iliakan** [comment]
I don't know what is GBK.
Surprised to see someone using this toy :)

It's well-written though, so have fun.

**Comment by tmcyfy** [comment]
yes  i like it.
GBK is chinese string.
I change here
`    telnetInput.pipe(through2(function(chunk, enc, callback) {
      chunk = iconv.decode(chunk, 'GBK');
      chunk = chunk.replace(/\r/g, '');
      callback(null, chunk);
    })).pipe(fse.createWriteStream('./logs/' + charName + '/' + Date.now() + '.log'));`

screen can show Chinese language.

but how can "telnetOutput" support the gbk or big5?

**Comment by iliakan** [comment]
You can send whatever you want through telnet. It uses UTF8 by default.
Don't know about big5 (only heard it exists).

**Comment by tmcyfy** [comment]
thanks you
