### ISSUE TITLE
Its me again, sorry )

### ISSUE THREAD

**Issue by trpx** [iliakan/mud-client#4]
Man, sorry for annoyance again, I promise this is the last one) I noticed that you also happened to build areas for the Dawn of Eternity MUD which I also had played.
Do you still have any contacts of people behind it or Solace?
And If you are willing to share the code for your areas, please send me, I would really appreciate anything related to these two muds as they were awesome ) xprt@yandex.com
I promise you won't here from me again if you don't wish to =)

**Comment by iliakan** [comment]
The person you need is probably Ivan Skalauh <skal@skal.ru> AKA Sonny.

He was running DoE and Solace (or rewritten Solace) for some time.

Here are my areas (by Atiel). I was very young at the time of writing them.
So my English was even farther from perfection than it's now, but some well-thought stuff and tales are still nice. Have fun and use them whereever you'd like ;)

[atiel.zip](https://github.com/iliakan/mud-client/files/2211879/atiel.zip)

**Comment by iliakan** [comment]
P.S. How did you find out I was building areas?

**Comment by trpx** [comment]
Thank you very much! you wrote about the areas here: https://github.com/iliakan/mud-client/blob/master/Readme.md :)  20.07.2018, 02:02, "Ilya Kantor" <notifications@github.com>:P.S. How did you find out I was building areas?—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.
